import React from 'react';
import {createRoot, hydrateRoot} from 'react-dom/client';
import App from './App';
import {PerformanceProvider} from './Performance';
import './styles.css';
import './experience.css';
import './art-direction.css';
import './style-worlds.css';
import './playback-refinements.css';
import './mobile-focus.css';
import './creative-refinements.css';
import './adaptive-performance.css';
import './idle-motion.css';
import './mobile-locked.css';
import './creative-process.css';
const node=document.getElementById('root')!;
const state=JSON.parse(document.getElementById('page-state')?.textContent || '{}');
const app=<PerformanceProvider><App initialPath={state.path || '/'} /></PerformanceProvider>;
if(node.innerHTML.includes('data-app')) hydrateRoot(node,app); else createRoot(node).render(app);
